### ISSUE TITLE
Nuked-OPL3 drop-in replacement

### ISSUE THREAD

**Issue by rofl0r** [digital-sound-antiques/emu8950#2]
hello, i am biting my teeth out trying to make emu8950 a drop-in replacement for nuked-opl3 in this simple app: https://github.com/cmdrf/droplay .
it is a player for dosbox' OPL captures in DRO format, so what it does is basically just feeding any recorded raw OPL commands to the OPL "chip", which in nuked's case is blackbox-like: the only interface are register writes whereas emu8950 has a way more sophisticated (and complicated) API. The reason i want to use emu8950 there is three-fold: 1) nuked produces a heavy CPU load, 2) it uses a LGPL license 3) my favorite tune https://github.com/Malvineous/dro2midi/blob/master/testcases/sango_fighter_title_drov2.dro plays some drums at about 0:22 which sound very bad with nuked, so i need to figure out whether the culprit is dosbox capturing an insufficient amount of state or nuked messing up the output due to some bug.

as for the difficulties i have with emu8950:

1) it's unclear why OPL_calcStereo returns 2 int32_t whereas OPL_calc returns an int16_t as expected and what to do to convert those into 16 bit samples
2) it's unclear what the difference between OPL_writeIO and OPL_writeReg is (at least to someone like me not very familiar with the intrinsics of sound chips)
3) how delays are to be treated and when to feed/read data into or out from the chip. i suspect i'll have to emulate the clock cycle timing of an MSX and in case of delays just grab a sample from the chip every X nanoseconds.
4) whether emu8950 needs additional setup data like this: https://github.com/Wohlstand/scc/blob/master/emidi_alpha/device/2413tone.h (the dosbox DRO format contains a capture of initial state of the OPL registers, so theoretically this should be sufficient)

i'd be glad for any hints you can provide, thanks!

**Comment by rofl0r** [comment]
i finally managed to figure out the semantics and get it working: https://github.com/rofl0r/libdroplay/commit/ecdfd256e83109b4884859414dd36b272348cf4a

i'd still like to know points 1 and 2 in my list, the other 2 were resolved after studying the wavewriter example in your OPLL repo.

**Comment by okaxaki** [comment]
Hi, 

The main reason i continue to publish emu8950 is exactly the same: 1) CPU load, 2) License. I'm glad it seems to have matched your purpose.

> 1. it's unclear why OPL_calcStereo returns 2 int32_t whereas OPL_calc returns an int16_t as expected and what to do to convert those into 16 bit samples

Currently int16_t is enough also for OPL_calcStereo, but I still keep it int32_t for backward compatibility.

> 2. it's unclear what the difference between OPL_writeIO and OPL_writeReg is (at least to someone like me not very familiar with the intrinsics of sound chips)

OPLwriteReg is used to write a value to the specific register. I think this funcation is intuitive. On the other hand, OPL_writeIO is for setting the register address and value separately; It is useful for connecting emu8950 to Z80 emulator engines.

```
OPL_writeIO(opl, 0, 0x10); // set address to 0x10
OPL_writeIO(opl, 1, 0x01); // same as OPL_writeReg(opl, 0x10, 0x01);
OPL_writeIO(opl, 1, 0x02); // same as OPL_writeReg(opl, 0x10, 0x02);
```

Thanks!

**Comment by rofl0r** [comment]
> Currently int16_t is enough also for OPL_calcStereo, but I still keep it int32_t for backward compatibility.

ah alright. so i guess one can just use the result & 0xffff.

> OPL_writeIO is for setting the register address and value separately

ah, interesting.

meanwhile i tried nuked, emu8950 and dosbox "woody", but neither of them plays the mentioned drums in the DRO correctly... so there's still some work ahead.

anyways, thanks for providing this excellent library and for your explanations!
