### ISSUE TITLE
opl2 emulation missing notes

### ISSUE THREAD

**Issue by eeprom1** [digital-sound-antiques/emu8950#3]
Playing vgm capture of prince of persia, the intro is missing some notes, also the danger music is missing a lot of notes. 
I attached vgm captures and wave recroding.
Please rename first two files to VGZ extension and last file to WAV
[01PROL1.pdf](https://github.com/user-attachments/files/15539442/01PROL1.pdf)
[06DANG1.pdf](https://github.com/user-attachments/files/15539447/06DANG1.pdf)
[princeofpersia_issue.pdf](https://github.com/user-attachments/files/15539454/princeofpersia_issue.pdf)

**Comment by okaxaki** [comment]
Thank you. 
An necessary rate-key-scale calculation step at key-on was skipped due to excessive optimization. Fixed at commit  [570dc99](https://github.com/digital-sound-antiques/emu8950/commit/570dc998dd83cee87b021e15e1d86da736934393).
